-- =============================================================================
-- 1. SETUP & EXTENSIONS
-- =============================================================================
-- Enable UUID extension for generating unique IDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- 2. PUBLIC TABLES
-- =============================================================================

-- A. ORGANIZATIONS (The Tenant)
-- All users and data belong to one of these.
CREATE TABLE public.organizations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- B. PROFILES (Users)
-- Extends the standard Supabase auth.users table with app-specific data.
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    organization_id UUID REFERENCES public.organizations(id),
    full_name TEXT,
    avatar_url TEXT,
    role TEXT CHECK (role IN ('ADMIN', 'MEMBER', 'VIEWER')) DEFAULT 'MEMBER',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- C. PROJECTS
-- Workspaces for your engineering reports.
CREATE TABLE public.projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    created_by UUID REFERENCES public.profiles(id),
    name TEXT NOT NULL,
    description TEXT,
    status TEXT CHECK (status IN ('ACTIVE', 'ARCHIVED', 'COMPLETED')) DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- D. KNOWLEDGE_ITEMS (RAG / Files)
-- Metadata for the files you uploaded (PDFs, Word Docs).
-- Note: Actual vectors are in Pinecone, but we track the status here.
CREATE TABLE public.knowledge_items (
    k_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    organization_id UUID NOT NULL REFERENCES public.organizations(id), -- Denormalized for faster RLS
    document_type TEXT CHECK (document_type IN ('PDF', 'WORD', 'TEXT')),
    original_file_name TEXT NOT NULL,
    storage_path TEXT, -- Optional: path if you store file in Supabase Storage
    content TEXT, -- Extracted raw text (optional, but good for debugging)
    status TEXT CHECK (status IN ('PROCESSING', 'INDEXED', 'FAILED')) DEFAULT 'PROCESSING',
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- E. REPORTS
-- The final output documents generated by the AI.
CREATE TABLE public.reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),
    title TEXT,
    content JSONB, -- Storing structured content (sections, paragraphs)
    template_id TEXT, -- Changed from UUID to TEXT to support string slugs like "observation"
    status TEXT DEFAULT 'DRAFT', -- Added status column
    version_number INTEGER DEFAULT 1,
    sections JSONB, -- Adding sections column as per repository usage
    created_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- F. CHAT SESSIONS
-- History of conversations.
CREATE TABLE public.chat_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),
    user_id UUID REFERENCES public.profiles(id),
    title TEXT DEFAULT 'New Chat',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- G. CHAT MESSAGES
-- Individual messages inside a session.
CREATE TABLE public.chat_messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
    role TEXT CHECK (role IN ('user', 'assistant', 'system')) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================================================
-- 3. ASSETS (Updated for Storage Buckets)
-- =============================================================================

-- 1. THE MASTER GALLERY (Represents the file in the bucket)
CREATE TABLE public.project_images (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),

    -- STORAGE BUCKET FIELDS
    storage_path TEXT NOT NULL,  -- e.g., "project-123/site-visit/photo-1.jpg" (Used for deletion/download)
    public_url TEXT NOT NULL,    -- e.g., "https://xyz.supabase.co/storage/v1/object/public/..." (Used for <img> src)

    -- METADATA
    file_name TEXT,              -- Original filename (e.g., "IMG_2024.jpg")
    mime_type TEXT,              -- e.g., "image/jpeg"
    size_bytes BIGINT,           
    
    folder_name TEXT,            -- Folder/Category name (e.g., "Kitchen", "Living Room")
    description TEXT,            -- User provided description or AI generated

    -- AI ANALYSIS (Generated by SitePhotoAgent)
    ai_description TEXT,         -- AI-generated markdown description from vision analysis
    tags TEXT[],                 -- AI-extracted tags (e.g., ["water damage", "safety hazard"])
    severity TEXT CHECK (severity IN ('Low', 'Medium', 'High', 'Critical', 'None')), -- AI-assessed severity

    -- CONTEXT
    uploaded_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- GEOSPATIAL (Optional but good for reports)
    gps_latitude DOUBLE PRECISION,
    gps_longitude DOUBLE PRECISION
);

-- 2. THE REPORT USAGE (Links an image to a report)
CREATE TABLE public.report_images (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    report_id UUID NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
    image_id UUID NOT NULL REFERENCES public.project_images(id) ON DELETE CASCADE,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),
    
    -- Context specific to THIS report
    caption TEXT,                -- "Crack in north wall" (Specific to this report)
    ai_description TEXT,         -- AI-generated description from vision analysis (report builder)
    sort_order INTEGER DEFAULT 0, -- To keep images in order
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Prevent adding the same image to the same report twice
    UNIQUE(report_id, image_id)
);

-- =============================================================================
-- 3. ROW LEVEL SECURITY (RLS) - The "Firewall"
-- =============================================================================
-- Enable RLS
ALTER TABLE public.report_images ENABLE ROW LEVEL SECURITY;

-- Add Policy
CREATE POLICY "Org report images" ON public.report_images 
FOR ALL USING (organization_id = get_auth_org_id());
-- Enable RLS on all tables
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- --- HELPER FUNCTION ---
-- This function checks if the current user belongs to the requested organization.
-- It prevents us from writing complex subqueries in every policy.
CREATE OR REPLACE FUNCTION public.get_auth_org_id()
RETURNS UUID AS $$
BEGIN
  RETURN (SELECT organization_id FROM public.profiles WHERE id = auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- --- POLICIES ---

-- 1. PROFILES
-- Users can read profiles of people in their SAME organization.
CREATE POLICY "View org members" ON public.profiles
FOR SELECT USING (organization_id = get_auth_org_id());

-- Users can update their OWN profile.
CREATE POLICY "Update own profile" ON public.profiles
FOR UPDATE USING (auth.uid() = id);

-- 2. ORGANIZATIONS
-- Users can see their own organization.
CREATE POLICY "View own org" ON public.organizations
FOR SELECT USING (id = get_auth_org_id());

-- 3. PROJECTS
-- Users can CRUD projects if they belong to the project's organization.
CREATE POLICY "Access projects in own org" ON public.projects
FOR ALL USING (organization_id = get_auth_org_id());

-- 4. KNOWLEDGE ITEMS
CREATE POLICY "Access knowledge in own org" ON public.knowledge_items
FOR ALL USING (organization_id = get_auth_org_id());

-- 5. REPORTS
CREATE POLICY "Access reports in own org" ON public.reports
FOR ALL USING (organization_id = get_auth_org_id());

-- 6. CHAT SESSIONS
CREATE POLICY "Access chats in own org" ON public.chat_sessions
FOR ALL USING (organization_id = get_auth_org_id());

-- 7. CHAT MESSAGES
-- We check the SESSION's organization to secure the message.
CREATE POLICY "Access messages via session org" ON public.chat_messages
FOR ALL USING (
    exists (
        select 1 from public.chat_sessions s
        where s.id = chat_messages.session_id
        and s.organization_id = get_auth_org_id()
    )
);

-- =============================================================================
-- 4. TRIGGERS (Auto-update Timestamps)
-- =============================================================================

-- Function to handle 'updated_at' automatically
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply triggers
CREATE TRIGGER update_projects_updated_at BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_reports_updated_at BEFORE UPDATE ON public.reports FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- =============================================================================
-- 5. NEW USER HANDLER (Supabase Auth Hook)
-- =============================================================================
-- This automatically creates a row in 'public.profiles' when a user signs up.
-- NOTE: For simplicity, we are putting them in a "Default Org" or leaving org null.
-- In a real SaaS, you would assign this during the onboarding flow.

CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger the function on new signups
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
