import { AgentStrategy, AgentExecutionContext } from "../interfaces";

export class GemminiAgent implements AgentStrategy {
  async generateContent(context: AgentExecutionContext): Promise<string> {
    console.log("🤖 GPT-4: Processing with OpenAI API...");
    // Real logic: await openai.chat.completions.create({...})
    return "Report generated by GPT-4";
  }
}